from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.constants import CardioType, Category, HomeEquipment, Level, Location, MuscleGroup, TrainingType


# --- Exercises ---


class ExerciseSummary(BaseModel):
    id: int
    name: str
    muscle_group: str
    category: str

    model_config = ConfigDict(from_attributes=True)


class ExerciseRead(ExerciseSummary):
    level: str
    requires_gym: bool
    is_cardio: bool
    cardio_type: str | None
    is_hyrox: bool
    rx_weight_male_kg: float | None
    rx_weight_female_kg: float | None
    description: str | None


# --- Fixed WODs ---


class FixedWodRead(BaseModel):
    id: int
    name: str
    wod_category: str
    description: str
    structure: str
    time_cap_minutes: int | None

    model_config = ConfigDict(from_attributes=True)


# --- Predefined WODs ---


class PredefinedWodMovementSummary(BaseModel):
    exercise_name: str
    reps: int | None = None
    distance_meters: int | None = None
    calories: int | None = None


class PredefinedWodSummary(BaseModel):
    id: int
    name: str
    training_type: str
    description: str
    duration_minutes: int
    level: str
    movements: list[PredefinedWodMovementSummary]


# --- Injuries ---


class InjuryCreate(BaseModel):
    description: str = Field(min_length=1, max_length=200)
    affected_muscle_group: MuscleGroup | None = None


class InjuryRead(InjuryCreate):
    id: int

    model_config = ConfigDict(from_attributes=True)


# --- Profiles ---


class ProfileCreate(BaseModel):
    user_id: str = Field(min_length=1, max_length=64)
    name: str = Field(min_length=1, max_length=80)


class ProfileUpdate(BaseModel):
    name: str | None = None
    # explicit null clears the level (turns off niveau-filtering)
    level: Level | None = None
    default_location: Location | None = None
    use_profile_level_default: bool | None = None
    home_equipment: list[HomeEquipment] | None = None


class ProfileRead(BaseModel):
    id: int
    user_id: str
    name: str
    level: str | None
    default_location: str
    use_profile_level_default: bool
    home_equipment: list[str] = []
    created_at: datetime
    injuries: list[InjuryRead] = []
    excluded_exercises: list[ExerciseSummary] = []

    model_config = ConfigDict(from_attributes=True)


class ExcludedExerciseAdd(BaseModel):
    exercise_id: int


# --- Friendships ---


class FriendRequestCreate(BaseModel):
    friend_user_id: str = Field(min_length=1, max_length=64)


class FriendshipUpdate(BaseModel):
    status: Literal["accepted"]


class FriendshipRead(BaseModel):
    id: int
    friend_user_id: str
    friend_name: str
    status: str
    direction: Literal["outgoing", "incoming"]


# --- WOD generation ---


class WodGenerateRequest(BaseModel):
    user_id: str = Field(min_length=1, max_length=64)
    length_minutes: int = Field(ge=5, le=90)
    muscle_groups: list[MuscleGroup] = Field(min_length=1)
    training_type: TrainingType
    location: Location
    include_cardio: bool = False
    cardio_type: CardioType | None = None
    # overrides the automatically computed number of cardio pieces when set
    cardio_count: int | None = Field(default=None, ge=1, le=4)
    include_warmup: bool = False
    warmup_minutes: int | None = Field(default=None, ge=3, le=20)
    # overrides the default of 3 warm-up exercises when set
    warmup_exercise_count: int | None = Field(default=None, ge=1, le=8)
    # only honored when the profile's use_profile_level_default is False
    deviate_level: Level | None = None
    # empty = fully auto-generated by the WOD generator
    chosen_exercise_ids: list[int] = []
    # exercise_id -> user's own weight in kg
    own_weights: dict[int, float] = {}
    # transient display hint only, never persisted on the profile
    sex: Literal["male", "female"] | None = None
    # overrides the automatically computed number of main-block exercises when set
    exercise_count: int | None = Field(default=None, ge=1, le=10)
    # categories to prioritize when auto-filling exercise slots (e.g. prefer barbell/dumbbell)
    preferred_categories: list[Category] = []
    # restricts exercise selection to Hyrox-tagged movements and favors extra cardio pieces
    hyrox_style: bool = False


class ExerciseInWod(BaseModel):
    exercise_id: int
    name: str
    muscle_group: str
    category: str
    reps: int | None = None
    duration_seconds: int | None = None
    distance_meters: int | None = None
    calories: int | None = None
    # assault_bike, ski_erg, row, run - only set for cardio exercises. Lets the frontend
    # recompute a correct distance/calorie value when swapping to another cardio exercise.
    cardio_type: str | None = None
    own_weight_kg: float | None = None
    suggested_weight_male_kg: float | None = None
    suggested_weight_female_kg: float | None = None
    alternatives: list[ExerciseSummary] = []


class WodBlock(BaseModel):
    block_type: Literal["warmup", "main", "cardio"]
    training_type: str | None = None
    duration_minutes: int
    # e.g. 5, or "AMRAP"
    rounds: int | str | None = None
    interval_seconds: int | None = None
    # e.g. "21-15-9", "flat"
    rep_scheme: str | None = None
    exercises: list[ExerciseInWod]


class GeneratedWod(BaseModel):
    profile_id: int
    location: str
    level_used: str | None
    total_duration_minutes: int
    blocks: list[WodBlock]
    generated_at: datetime


# --- History ---


class HistoryCreate(BaseModel):
    user_id: str = Field(min_length=1, max_length=64)
    source: Literal["generated", "fixed"]
    fixed_wod_id: int | None = None
    # GeneratedWod.model_dump() for "generated", a small snapshot dict for "fixed"
    wod_json: dict
    result: str | None = None


class HistoryUpdate(BaseModel):
    result: str | None = Field(default=None, max_length=100)
    note: str | None = Field(default=None, max_length=500)
    favorite: bool | None = None


class HistoryRead(BaseModel):
    id: int
    profile_id: int
    created_at: datetime
    source: str
    fixed_wod_id: int | None
    wod_json: dict
    result: str | None
    note: str | None = None
    favorite: bool = False


# --- Favorites (bookmarked library items - fixed/predefined WODs, not logged history) ---


class FavoriteCreate(BaseModel):
    user_id: str = Field(min_length=1, max_length=64)
    item_type: Literal["fixed_wod", "predefined_wod"]
    item_id: int


class FavoriteRead(BaseModel):
    item_type: str
    item_id: int
