# Curated starter set of "voorgedefinieerde workouts" (workout-ideeen), grouped by
# training_type so the frontend can offer an AMRAP / EMOM / Tabata / Anders (FOR_TIME)
# browse menu. Structures (rep schemes, time domains, movement combos) are based on
# well-established, publicly documented CrossFit programming patterns for each training
# type - not reproductions of specific named benchmark WODs (those live in fixed_wods.py).
# Every movement references an exercise name that must exist in seed/exercises.py; the
# seeder resolves these names to Exercise ids at insert time.
#
# rounds_override/rep_scheme_override are only read for training_type == "FOR_TIME" (see
# wod_generator._shape_predefined) - AMRAP/EMOM/TABATA derive their shape automatically.
PREDEFINED_WODS = [
    # --- AMRAP ---
    {
        "name": "Full Body Blast",
        "training_type": "AMRAP",
        "description": "Laagdrempelige full-body AMRAP om je conditie op te bouwen.",
        "duration_minutes": 12,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 15},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Sit-up", "reps": 15},
        ],
    },
    {
        "name": "Pull & Push Power",
        "training_type": "AMRAP",
        "description": "Bovenlichaam-AMRAP die trekkracht, duwkracht en een sprong combineert.",
        "duration_minutes": 15,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 8},
            {"exercise_name": "DB Shoulder Press", "reps": 10},
            {"exercise_name": "Box Jump", "reps": 12},
        ],
    },
    {
        "name": "Engine Builder",
        "training_type": "AMRAP",
        "description": "Hoog tempo AMRAP die kracht en conditie combineert.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 200},
        ],
    },
    {
        "name": "Heavy Metal",
        "training_type": "AMRAP",
        "description": "Zware AMRAP voor gevorderden met deadlifts en push press.",
        "duration_minutes": 20,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 10},
            {"exercise_name": "Push Press", "reps": 8},
            {"exercise_name": "Box Jump", "reps": 12},
        ],
    },
    {
        "name": "Endurance Grinder",
        "training_type": "AMRAP",
        "description": "Lange uithoudings-AMRAP met gymnastiek en een hardloopstuk.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    # --- Buddy WOD (1, AMRAP) - I-Go-You-Go format: one partner works a full round while
    # the other rests, then switches. See the FOR_TIME/EMOM sections below for the other two
    # partner formats (split-reps, synchro). is_buddy=True surfaces the "Buddy WOD"-filter/tag.
    {
        "name": "I-Go-You-Go Sprint",
        "training_type": "AMRAP",
        "description": "I-Go-You-Go: partner A doet 1 ronde, dan rust terwijl partner B dezelfde ronde doet. Wissel na elke ronde - samen zoveel mogelijk ronden in de tijd.",
        "duration_minutes": 20,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing American", "reps": 12},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Air Squat", "reps": 15},
        ],
    },
    # --- Long Hyrox-style AMRAPs (10) - user-supplied, 45 min multi-station chippers.
    # A few movements without a direct equivalent are substituted with the closest existing
    # exercise: Sandbag Carry -> DB/KB Farmers Carry (documented stand-in, see exercises.py),
    # Box Step-Up/Step-Over -> Box Step-Up. Ambiguous "Farmer Carry" (no DB/KB specified in the
    # source) is resolved per-WOD to whichever implement the rest of that WOD already uses.
    {
        "name": "Hyrox Engine Builder",
        "training_type": "AMRAP",
        "description": "Lange Hyrox-stijl AMRAP met skien, roeien en een dragende afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "DB Thruster", "reps": 12},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Grinder",
        "training_type": "AMRAP",
        "description": "Hyrox-stijl chipper met hardlopen, wall balls en een sled-achtige afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Full Body (Hyrox)",
        "training_type": "AMRAP",
        "description": "Lange full-body AMRAP met barbell, kettlebell en hardlopen.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 10},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
        ],
    },
    {
        "name": "Grip & Engine",
        "training_type": "AMRAP",
        "description": "Grip-intensieve AMRAP: skien, dragen en kettlebell-kracht.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Strong Legs",
        "training_type": "AMRAP",
        "description": "Lange beenintensieve AMRAP met hardlopen, lunges en wall balls.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 600},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 300},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Russian Twist", "reps": 20},
        ],
    },
    {
        "name": "Hybrid",
        "training_type": "AMRAP",
        "description": "Hybride AMRAP die skien, snatches en hardlopen combineert.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "calories": 20},
            {"exercise_name": "DB Snatch", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Long Engine",
        "training_type": "AMRAP",
        "description": "Uithoudings-chipper met een lange roeiafstand en tussenstops.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 1000},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Functional Fitness",
        "training_type": "AMRAP",
        "description": "Klassieke Hyrox-stijl functionele AMRAP met thrusters en wall balls.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Style",
        "training_type": "AMRAP",
        "description": "Lange Hyrox-stijl AMRAP met hardlopen, wall balls en burpee broad jumps.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 25},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Endurance Chipper",
        "training_type": "AMRAP",
        "description": "Lange uithoudings-AMRAP met barbell, pull-ups en een dragende afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    # --- EMOM ---
    {
        "name": "Quick Starter",
        "training_type": "EMOM",
        "description": "Korte EMOM om kennis te maken met roterende oefeningen op de minuut.",
        "duration_minutes": 10,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 12},
            {"exercise_name": "Push-up", "reps": 10},
        ],
    },
    {
        "name": "Total Body Rotation",
        "training_type": "EMOM",
        "description": "EMOM die het hele lichaam laat roteren langs vier oefeningen.",
        "duration_minutes": 16,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 10},
            {"exercise_name": "Row", "calories": 12},
            {"exercise_name": "Sit-up", "reps": 15},
            {"exercise_name": "Box Jump", "reps": 10},
        ],
    },
    {
        "name": "Strength & Sweat",
        "training_type": "EMOM",
        "description": "Combineert een zware kniebuiging met conditiewerk op de minuut.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Back Squat", "reps": 5},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "KB Swing American", "reps": 12},
            {"exercise_name": "Double Unders", "reps": 20},
        ],
    },
    {
        "name": "Barbell Cycling",
        "training_type": "EMOM",
        "description": "Technische barbell-EMOM voor gevorderden: clean, squat en jerk.",
        "duration_minutes": 12,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Power Clean", "reps": 5},
            {"exercise_name": "Front Squat", "reps": 5},
            {"exercise_name": "Push Jerk", "reps": 5},
        ],
    },
    {
        "name": "Cardio Rotation",
        "training_type": "EMOM",
        "description": "Lange EMOM die cardiomachines afwisselt met kracht en gymnastiek.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 12},
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 8},
            {"exercise_name": "KB Clean", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    # --- Buddy WOD (1, EMOM) - alternating-minute format, the EMOM equivalent of I-Go-You-Go.
    {
        "name": "Buddy EMOM Engine",
        "training_type": "EMOM",
        "description": "EMOM om en om: in de oneven minuten werkt partner A, in de even minuten partner B - ieder je eigen oefening, samen 1 blok.",
        "duration_minutes": 16,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 12},
        ],
    },
    # --- TABATA ---
    {
        "name": "Tabata Classics",
        "training_type": "TABATA",
        "description": "De klassieke Tabata-combinatie: benen, borst en buik.",
        "duration_minutes": 16,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat"},
            {"exercise_name": "Push-up"},
            {"exercise_name": "Sit-up"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    {
        "name": "Kettlebell Tabata",
        "training_type": "TABATA",
        "description": "Korte, pittige Tabata met kettlebell-oefeningen.",
        "duration_minutes": 8,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "KB Swing Russian"},
            {"exercise_name": "Goblet Squat"},
        ],
    },
    {
        "name": "Engine Tabata",
        "training_type": "TABATA",
        "description": "Tabata gericht op conditie en core.",
        "duration_minutes": 12,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Burpee"},
            {"exercise_name": "Double Unders"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    {
        "name": "Upper Body Tabata",
        "training_type": "TABATA",
        "description": "Tabata die focust op borst, triceps en schouders.",
        "duration_minutes": 16,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Push-up"},
            {"exercise_name": "Ring Dip"},
            {"exercise_name": "Pike Push-up"},
            {"exercise_name": "DB Shoulder Press"},
        ],
    },
    {
        "name": "Full Send Tabata",
        "training_type": "TABATA",
        "description": "Vijf zware oefeningen kort na elkaar - een pittige conditietest.",
        "duration_minutes": 20,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Wall Ball Shot"},
            {"exercise_name": "Box Jump"},
            {"exercise_name": "KB Swing American"},
            {"exercise_name": "Burpee"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    # --- FOR_TIME ("Anders") ---
    {
        "name": "Classic Triplet",
        "training_type": "FOR_TIME",
        "description": "Klassiek dalend schema: 21-15-9 van twee oefeningen, zo snel mogelijk.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "3",
        "rep_scheme_override": "21-15-9",
        "movements": [
            {"exercise_name": "Thruster", "reps": 21},
            {"exercise_name": "Kipping Pull-up", "reps": 21},
        ],
    },
    {
        "name": "Chipper Challenge",
        "training_type": "FOR_TIME",
        "description": "Vijf oefeningen in aflopende reeks - werk je van veel naar weinig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend",
        "movements": [
            {"exercise_name": "Double Unders", "reps": 50},
            {"exercise_name": "Wall Ball Shot", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Burpee", "reps": 10},
        ],
    },
    {
        "name": "Deadlift Domination",
        "training_type": "FOR_TIME",
        "description": "Zwaar 21-15-9-schema met deadlifts en burpees.",
        "duration_minutes": 10,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "21-15-9",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 21},
            {"exercise_name": "Burpee", "reps": 21},
        ],
    },
    {
        "name": "Row & Grind",
        "training_type": "FOR_TIME",
        "description": "Rechttoe-rechtaan for-time workout met roeien en kracht.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Wall Ball Shot", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 40},
        ],
    },
    {
        "name": "The Ladder",
        "training_type": "FOR_TIME",
        "description": "Oplopende ladder tot 10 - hoe verder, hoe zwaarder.",
        "duration_minutes": 18,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "oplopende ladder 2-4-6-8-10",
        "movements": [
            {"exercise_name": "DB Snatch", "reps": 10},
            {"exercise_name": "Box Jump", "reps": 10},
        ],
    },
    # --- Buddy WODs (2, FOR_TIME) - split-reps and synchro, the other two partner formats
    # (see "I-Go-You-Go Sprint" above for the alternating one).
    {
        "name": "Buddy Chipper",
        "training_type": "FOR_TIME",
        "description": "Partner-chipper: verdeel de reps onderling zoals jullie willen, samen optellen tot het totaal hieronder. Ideaal om samen met een buddy te doen.",
        "duration_minutes": 25,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend, samen verdelen",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 80},
            {"exercise_name": "Box Jump", "reps": 60},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
            {"exercise_name": "Burpee", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
        ],
    },
    {
        "name": "Synchro Squat & Row",
        "training_type": "FOR_TIME",
        "description": "Synchro: voer de kniebuigingen tegelijk met je buddy uit - een rep telt pas als jullie gelijk zijn. Bij het roeien wissel je om de beurt af.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "synchro krachtdeel + afwisselend cardio",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Goblet Squat", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
]
