# Curated starter set of "voorgedefinieerde workouts" (workout-ideeen), grouped by
# training_type so the frontend can offer an AMRAP / EMOM / Tabata / Anders (FOR_TIME)
# browse menu. Structures (rep schemes, time domains, movement combos) are based on
# well-established, publicly documented CrossFit programming patterns for each training
# type - not reproductions of specific named benchmark WODs (those live in fixed_wods.py).
# Every movement references an exercise name that must exist in seed/exercises.py; the
# seeder resolves these names to Exercise ids at insert time.
#
# rounds_override/rep_scheme_override are only read for training_type == "FOR_TIME" (see
# wod_generator._shape_predefined) - AMRAP/EMOM/TABATA derive their shape automatically.
PREDEFINED_WODS = [
    # --- AMRAP ---
    {
        "name": "Full Body Blast",
        "training_type": "AMRAP",
        "description": "Laagdrempelige full-body AMRAP om je conditie op te bouwen.",
        "duration_minutes": 12,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 15},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Sit-up", "reps": 15},
        ],
    },
    {
        "name": "Pull & Push Power",
        "training_type": "AMRAP",
        "description": "Bovenlichaam-AMRAP die trekkracht, duwkracht en een sprong combineert.",
        "duration_minutes": 15,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 8},
            {"exercise_name": "DB Shoulder Press", "reps": 10},
            {"exercise_name": "Box Jump", "reps": 12},
        ],
    },
    {
        "name": "Engine Builder",
        "training_type": "AMRAP",
        "description": "Hoog tempo AMRAP die kracht en conditie combineert.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 200},
        ],
    },
    {
        "name": "Heavy Metal",
        "training_type": "AMRAP",
        "description": "Zware AMRAP voor gevorderden met deadlifts en push press.",
        "duration_minutes": 20,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 10},
            {"exercise_name": "Push Press", "reps": 8},
            {"exercise_name": "Box Jump", "reps": 12},
        ],
    },
    {
        "name": "Endurance Grinder",
        "training_type": "AMRAP",
        "description": "Lange uithoudings-AMRAP met gymnastiek en een hardloopstuk.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    # --- Buddy WOD (1, AMRAP) - I-Go-You-Go format: one partner works a full round while
    # the other rests, then switches. See the FOR_TIME/EMOM sections below for the other two
    # partner formats (split-reps, synchro). is_buddy=True surfaces the "Buddy WOD"-filter/tag.
    {
        "name": "I-Go-You-Go Sprint",
        "training_type": "AMRAP",
        "description": "I-Go-You-Go: partner A doet 1 ronde, dan rust terwijl partner B dezelfde ronde doet. Wissel na elke ronde - samen zoveel mogelijk ronden in de tijd.",
        "duration_minutes": 20,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing American", "reps": 12},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Air Squat", "reps": 15},
        ],
    },
    # --- Reisvriendelijke WOD's (3) - geïnspireerd op crossfit.com/essentials/travel-workouts-
    # stay-fit-this-summer (alleen het format/de opzet, geen letterlijke overname - zelfde aanpak
    # als de rest van dit bestand: "based on well-established programming patterns", zie boven).
    # Puur bodyweight, dus overal te doen, geen apparatuur nodig.
    {
        "name": "Overal Fit",
        "training_type": "AMRAP",
        "description": "Korte, overal-te-doen AMRAP - geen apparatuur nodig, ideaal op reis of thuis.",
        "duration_minutes": 10,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 10},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "Push-up", "reps": 10},
        ],
    },
    # --- Long Hyrox-style AMRAPs (10) - user-supplied, 45 min multi-station chippers.
    # A few movements without a direct equivalent are substituted with the closest existing
    # exercise: Sandbag Carry -> DB/KB Farmers Carry (documented stand-in, see exercises.py),
    # Box Step-Up/Step-Over -> Box Step-Up. Ambiguous "Farmer Carry" (no DB/KB specified in the
    # source) is resolved per-WOD to whichever implement the rest of that WOD already uses.
    {
        "name": "Hyrox Engine Builder",
        "training_type": "AMRAP",
        "description": "Lange Hyrox-stijl AMRAP met skien, roeien en een dragende afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "DB Thruster", "reps": 12},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Grinder",
        "training_type": "AMRAP",
        "description": "Hyrox-stijl chipper met hardlopen, wall balls en een sled-achtige afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Full Body (Hyrox)",
        "training_type": "AMRAP",
        "description": "Lange full-body AMRAP met barbell, kettlebell en hardlopen.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 10},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
        ],
    },
    {
        "name": "Grip & Engine",
        "training_type": "AMRAP",
        "description": "Grip-intensieve AMRAP: skien, dragen en kettlebell-kracht.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Strong Legs",
        "training_type": "AMRAP",
        "description": "Lange beenintensieve AMRAP met hardlopen, lunges en wall balls.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 600},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 300},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Russian Twist", "reps": 20},
        ],
    },
    {
        "name": "Hybrid",
        "training_type": "AMRAP",
        "description": "Hybride AMRAP die skien, snatches en hardlopen combineert.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "calories": 20},
            {"exercise_name": "DB Snatch", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Long Engine",
        "training_type": "AMRAP",
        "description": "Uithoudings-chipper met een lange roeiafstand en tussenstops.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 1000},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Functional Fitness",
        "training_type": "AMRAP",
        "description": "Klassieke Hyrox-stijl functionele AMRAP met thrusters en wall balls.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Style",
        "training_type": "AMRAP",
        "description": "Lange Hyrox-stijl AMRAP met hardlopen, wall balls en burpee broad jumps.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 25},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Endurance Chipper",
        "training_type": "AMRAP",
        "description": "Lange uithoudings-AMRAP met barbell, pull-ups en een dragende afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    # --- EMOM ---
    {
        "name": "Quick Starter",
        "training_type": "EMOM",
        "description": "Korte EMOM om kennis te maken met roterende oefeningen op de minuut.",
        "duration_minutes": 10,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 12},
            {"exercise_name": "Push-up", "reps": 10},
        ],
    },
    {
        "name": "Total Body Rotation",
        "training_type": "EMOM",
        "description": "EMOM die het hele lichaam laat roteren langs vier oefeningen.",
        "duration_minutes": 16,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 10},
            {"exercise_name": "Row", "calories": 12},
            {"exercise_name": "Sit-up", "reps": 15},
            {"exercise_name": "Box Jump", "reps": 10},
        ],
    },
    {
        "name": "Strength & Sweat",
        "training_type": "EMOM",
        "description": "Combineert een zware kniebuiging met conditiewerk op de minuut.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Back Squat", "reps": 5},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "KB Swing American", "reps": 12},
            {"exercise_name": "Double Unders", "reps": 20},
        ],
    },
    {
        "name": "Barbell Cycling",
        "training_type": "EMOM",
        "description": "Technische barbell-EMOM voor gevorderden: clean, squat en jerk.",
        "duration_minutes": 12,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Power Clean", "reps": 5},
            {"exercise_name": "Front Squat", "reps": 5},
            {"exercise_name": "Push Jerk", "reps": 5},
        ],
    },
    {
        "name": "Cardio Rotation",
        "training_type": "EMOM",
        "description": "Lange EMOM die cardiomachines afwisselt met kracht en gymnastiek.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 12},
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 8},
            {"exercise_name": "KB Clean", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    # --- Buddy WOD (1, EMOM) - alternating-minute format, the EMOM equivalent of I-Go-You-Go.
    {
        "name": "Buddy EMOM Engine",
        "training_type": "EMOM",
        "description": "EMOM om en om: in de oneven minuten werkt partner A, in de even minuten partner B - ieder je eigen oefening, samen 1 blok.",
        "duration_minutes": 16,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 12},
        ],
    },
    # --- TABATA ---
    {
        "name": "Tabata Classics",
        "training_type": "TABATA",
        "description": "De klassieke Tabata-combinatie: benen, borst en buik.",
        "duration_minutes": 16,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat"},
            {"exercise_name": "Push-up"},
            {"exercise_name": "Sit-up"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    {
        "name": "Kettlebell Tabata",
        "training_type": "TABATA",
        "description": "Korte, pittige Tabata met kettlebell-oefeningen.",
        "duration_minutes": 8,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "KB Swing Russian"},
            {"exercise_name": "Goblet Squat"},
        ],
    },
    {
        "name": "Engine Tabata",
        "training_type": "TABATA",
        "description": "Tabata gericht op conditie en core.",
        "duration_minutes": 12,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Burpee"},
            {"exercise_name": "Double Unders"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    {
        "name": "Upper Body Tabata",
        "training_type": "TABATA",
        "description": "Tabata die focust op borst, triceps en schouders.",
        "duration_minutes": 16,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Push-up"},
            {"exercise_name": "Ring Dip"},
            {"exercise_name": "Pike Push-up"},
            {"exercise_name": "DB Shoulder Press"},
        ],
    },
    {
        "name": "Full Send Tabata",
        "training_type": "TABATA",
        "description": "Vijf zware oefeningen kort na elkaar - een pittige conditietest.",
        "duration_minutes": 20,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Wall Ball Shot"},
            {"exercise_name": "Box Jump"},
            {"exercise_name": "KB Swing American"},
            {"exercise_name": "Burpee"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    # --- FOR_TIME ("Anders") ---
    {
        "name": "Classic Triplet",
        "training_type": "FOR_TIME",
        "description": "Klassiek dalend schema: 21-15-9 van twee oefeningen, zo snel mogelijk.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "3",
        "rep_scheme_override": "21-15-9",
        "movements": [
            {"exercise_name": "Thruster", "reps": 21},
            {"exercise_name": "Kipping Pull-up", "reps": 21},
        ],
    },
    {
        "name": "Chipper Challenge",
        "training_type": "FOR_TIME",
        "description": "Vijf oefeningen in aflopende reeks - werk je van veel naar weinig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend",
        "movements": [
            {"exercise_name": "Double Unders", "reps": 50},
            {"exercise_name": "Wall Ball Shot", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Burpee", "reps": 10},
        ],
    },
    {
        "name": "Deadlift Domination",
        "training_type": "FOR_TIME",
        "description": "Zwaar 21-15-9-schema met deadlifts en burpees.",
        "duration_minutes": 10,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "21-15-9",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 21},
            {"exercise_name": "Burpee", "reps": 21},
        ],
    },
    {
        "name": "Row & Grind",
        "training_type": "FOR_TIME",
        "description": "Rechttoe-rechtaan for-time workout met roeien en kracht.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Wall Ball Shot", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 40},
        ],
    },
    {
        "name": "The Ladder",
        "training_type": "FOR_TIME",
        "description": "Oplopende ladder tot 10 - hoe verder, hoe zwaarder.",
        "duration_minutes": 18,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "oplopende ladder 2-4-6-8-10",
        "movements": [
            {"exercise_name": "DB Snatch", "reps": 10},
            {"exercise_name": "Box Jump", "reps": 10},
        ],
    },
    # --- Buddy WODs (2, FOR_TIME) - split-reps and synchro, the other two partner formats
    # (see "I-Go-You-Go Sprint" above for the alternating one).
    {
        "name": "Buddy Chipper",
        "training_type": "FOR_TIME",
        "description": "Partner-chipper: verdeel de reps onderling zoals jullie willen, samen optellen tot het totaal hieronder. Ideaal om samen met een buddy te doen.",
        "duration_minutes": 25,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend, samen verdelen",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 80},
            {"exercise_name": "Box Jump", "reps": 60},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
            {"exercise_name": "Burpee", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
        ],
    },
    {
        "name": "Synchro Squat & Row",
        "training_type": "FOR_TIME",
        "description": "Synchro: voer de kniebuigingen tegelijk met je buddy uit - een rep telt pas als jullie gelijk zijn. Bij het roeien wissel je om de beurt af.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "synchro krachtdeel + afwisselend cardio",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Goblet Squat", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
    # --- Reisvriendelijke WOD's, vervolg (2, FOR_TIME) - zie de AMRAP-sectie hierboven voor de
    # bron/aanpak-toelichting.
    {
        "name": "Thuis Chipper",
        "training_type": "FOR_TIME",
        "description": "Aflopende chipper zonder apparatuur - overal te doen, ook op reis.",
        "duration_minutes": 18,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend 60-50-40-30-20",
        "movements": [
            {"exercise_name": "Sit-up", "reps": 60},
            {"exercise_name": "Walking Lunge", "reps": 50},
            {"exercise_name": "Push-up", "reps": 40},
            {"exercise_name": "Bodyweight Good Morning", "reps": 30},
            {"exercise_name": "Burpee", "reps": 20},
        ],
    },
    {
        "name": "Hardloop & Burpees",
        "training_type": "FOR_TIME",
        "description": "3 ronden hardlopen en burpee broad jumps - simpel op te bouwen, overal en altijd te doen zolang je buiten kunt hardlopen.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "3",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    # --- Buddy WODs, vervolg (2, FOR_TIME) - geïnspireerd op echte partner-WOD's van
    # outdoormusclefit.com/partner-crossfit-workouts (format/opzet, geen letterlijke overname -
    # zelfde aanpak als de rest van dit bestand). "Buffalo 10" introduceert een 4e partnerformaat
    # naast I-Go-You-Go/split-reps/synchro: station-rotatie, waarbij je samen door dezelfde
    # oefeningen roteert (na elke oefening van plek wisselen) i.p.v. samen te werken op 1 oefening.
    {
        "name": "Buffalo 10",
        "training_type": "FOR_TIME",
        "description": "Station-rotatie: na elke oefening wissel je met je buddy van plek. Het hardloopstuk doe je samen.",
        "duration_minutes": 30,
        "level": "intermediate",
        "rounds_override": "10",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Deadlift", "reps": 5},
            {"exercise_name": "Push-up", "reps": 14},
            {"exercise_name": "Double Unders", "reps": 22},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Pulse",
        "training_type": "FOR_TIME",
        "description": "Synchro: de burpees doe je gelijktijdig met je buddy - een rep telt pas als jullie gelijk zijn. De rest van de ronde en het hardloopstuk doe je om de beurt.",
        "duration_minutes": 25,
        "level": "advanced",
        "rounds_override": "6",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Burpee", "reps": 12},
            {"exercise_name": "KB Swing Russian", "reps": 16},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },

    # --- Reisvriendelijke WOD's, aanvulling 2 (4) - crossfit.com/essentials/travel-workouts
    # bevat in totaal maar 9 workouts (geen paginering/verborgen content - dubbel-gecheckt).
    # 3 daarvan staan al hierboven; dit zijn de overige bruikbare (2 pasten niet goed: een sets-
    # met-rust-interval-format past niet op AMRAP/EMOM/FOR_TIME, en 1 was te dun als losstaand
    # idee). "Plank Up-Down" is nieuw toegevoegd aan exercises.py voor #4 hieronder.
    {
        "name": "Sprint & Plank",
        "training_type": "AMRAP",
        "description": "Cardio en core afwisselend - overal te doen, alleen wat ruimte om te rennen nodig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Plank Up-Down", "reps": 20},
        ],
    },
    {
        "name": "Bodyweight EMOM",
        "training_type": "EMOM",
        "description": "Wisselende bodyweight-oefening elke minuut - geen apparatuur nodig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 12},
            {"exercise_name": "Burpee", "reps": 12},
            {"exercise_name": "Pike Push-up", "reps": 12},
            {"exercise_name": "V-up", "reps": 12},
        ],
    },
    {
        "name": "Deadlift & Core AMRAP",
        "training_type": "AMRAP",
        "description": "Combinatie van kracht en core - werkt met een halterstang of een zwaar object (bijv. een volle tas) als je thuis geen gewichten hebt.",
        "duration_minutes": 15,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 10},
            {"exercise_name": "V-up", "reps": 15},
            {"exercise_name": "Air Squat", "reps": 15},
        ],
    },

    # --- Buddy WODs, aanvulling (19) - outdoormusclefit.com/partner-crossfit-workouts bevat 50
    # partner-WOD's; dit is een selectie die goed past bij de bestaande oefeningen-catalogus,
    # met gematigder volume dan de originele (vaak extreme) hero-WOD-achtige aantallen - passend
    # bij dit project se "simpel en toegankelijk" uitgangspunt. Formaat/opzet overgenomen, geen
    # letterlijke tekst. "Save Connor" introduceert een 5e partnerformaat: concurrent-verschillend-
    # werk (partners doen tegelijk andere oefeningen, wisselen na een ronde) naast I-Go-You-Go/
    # split-reps/synchro/station-rotatie.
    {
        "name": "Howdy Partner",
        "training_type": "FOR_TIME",
        "description": "Samen op de Airbike, verdeel de Rope Climbs en Deadlifts onderling.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Rope Climb", "reps": 6},
            {"exercise_name": "Deadlift", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Eva Strong",
        "training_type": "FOR_TIME",
        "description": "Double-unders samen, Toes-to-Bar en Clean and Jerk verdeel je onderling.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Double Unders", "reps": 24},
            {"exercise_name": "Toes-to-Bar", "reps": 15},
            {"exercise_name": "Clean and Jerk", "reps": 2},
        ],
    },
    {
        "name": "Friendly Murph",
        "training_type": "FOR_TIME",
        "description": "Partner-versie van Murph: verdeel de pull-ups, push-ups en squats onderling zoals jullie willen. Het hardlopen doe je samen.",
        "duration_minutes": 45,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "samen verdelen",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1600},
            {"exercise_name": "Kipping Pull-up", "reps": 100},
            {"exercise_name": "Push-up", "reps": 200},
            {"exercise_name": "Air Squat", "reps": 300},
            {"exercise_name": "Running", "distance_meters": 1600},
        ],
    },
    {
        "name": "Barbell Bros",
        "training_type": "FOR_TIME",
        "description": "Verdeel de barbell-reps zoals jullie willen. Het hardlopen doe je samen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1600},
            {"exercise_name": "Front Squat", "reps": 50},
            {"exercise_name": "Push Jerk", "reps": 30},
            {"exercise_name": "Walking Lunge", "reps": 30},
        ],
    },
    {
        "name": "Miller",
        "training_type": "FOR_TIME",
        "description": "I-Go-You-Go: wissel elke ronde af met je buddy.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "10",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "DB Walking Lunge", "reps": 14},
        ],
    },
    {
        "name": "Hannah",
        "training_type": "FOR_TIME",
        "description": "Verdeel de ronden met je buddy. Sluit samen af met de hardloop-cash-out.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "8",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Burpee Box Jump Over", "reps": 7},
            {"exercise_name": "Running", "distance_meters": 2000},
        ],
    },
    {
        "name": "Save Connor",
        "training_type": "FOR_TIME",
        "description": "Concurrent: terwijl partner A rent, doet partner B tegelijk het krachtblok. Wissel na elke ronde.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "6",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 600},
            {"exercise_name": "DB Romanian Deadlift", "reps": 12},
            {"exercise_name": "KB Swing Russian", "reps": 12},
            {"exercise_name": "DB Thruster", "reps": 12},
        ],
    },
    {
        "name": "Cash",
        "training_type": "AMRAP",
        "description": "Samen zoveel mogelijk ronden - werk of wissel af zoals jullie willen.",
        "duration_minutes": 20,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
        ],
    },
    {
        "name": "Ares",
        "training_type": "AMRAP",
        "description": "Samen zoveel mogelijk ronden - werk of wissel af zoals jullie willen.",
        "duration_minutes": 16,
        "level": "advanced",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 15},
            {"exercise_name": "GHD Sit-up", "reps": 12},
            {"exercise_name": "Box Jump Over", "reps": 10},
        ],
    },
    {
        "name": "TWR Pride WOD",
        "training_type": "AMRAP",
        "description": "De burpees doe je synchroon met je buddy. De rest van de ronde doe je om de beurt.",
        "duration_minutes": 20,
        "level": "advanced",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Squat Clean", "reps": 6},
            {"exercise_name": "Burpee", "reps": 6},
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "DB Snatch", "reps": 14},
        ],
    },
    {
        "name": "Barber Pole",
        "training_type": "FOR_TIME",
        "description": "I-Go-You-Go op één oefening: wissel elke 25 cal met je buddy.",
        "duration_minutes": 8,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 25},
        ],
    },
    {
        "name": "CBC Qualifier 21.2",
        "training_type": "FOR_TIME",
        "description": "Verdeel de reps met je buddy zoals jullie willen.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Front Squat", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 30},
            {"exercise_name": "Thruster", "reps": 15},
        ],
    },
    {
        "name": "Noah Calderon",
        "training_type": "FOR_TIME",
        "description": "Verdeel de ronden met je buddy zoals jullie willen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "8",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Deadlift", "reps": 3},
            {"exercise_name": "KB Swing Russian", "reps": 8},
            {"exercise_name": "Box Jump", "reps": 12},
            {"exercise_name": "Burpee", "reps": 20},
        ],
    },
    {
        "name": "Honey Badger",
        "training_type": "AMRAP",
        "description": "Samen zoveel mogelijk ronden. Het hardlopen doe je samen.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Squat Clean", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Running", "distance_meters": 800},
        ],
    },
    {
        "name": "Taylor 91",
        "training_type": "FOR_TIME",
        "description": "Verdeel de reps met je buddy zoals jullie willen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 30},
            {"exercise_name": "Overhead Press", "reps": 30},
            {"exercise_name": "Front Squat", "reps": 30},
            {"exercise_name": "Burpee", "reps": 30},
        ],
    },
    {
        "name": "Uplift",
        "training_type": "FOR_TIME",
        "description": "Grote chipper - verdeel de reps met je buddy zoals jullie willen. Roeien doe je samen.",
        "duration_minutes": 30,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Squat Clean", "reps": 10},
            {"exercise_name": "Row", "distance_meters": 1800},
            {"exercise_name": "Double Unders", "reps": 100},
            {"exercise_name": "Burpee", "reps": 40},
            {"exercise_name": "Deadlift", "reps": 30},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
        ],
    },
    {
        "name": "We Remember",
        "training_type": "FOR_TIME",
        "description": "Terwijl de een klimt, houdt de ander een Plank Hold vol - wissel af tot het klimmen klaar is. Het hardlopen doe je samen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Rope Climb", "reps": 9},
            {"exercise_name": "Running", "distance_meters": 1600},
        ],
    },
    {
        "name": "Muhammad Ali",
        "training_type": "FOR_TIME",
        "description": "Verdeel de reps met je buddy zoals jullie willen. Het hardlopen doe je samen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "Clean and Jerk", "reps": 20},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Toes-to-Bar", "reps": 20},
        ],
    },
    {
        "name": "Move Forward",
        "training_type": "FOR_TIME",
        "description": "Synchro: elke oefening doe je gelijktijdig met je buddy - een rep telt pas als jullie gelijk zijn.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "4",
        "rep_scheme_override": "synchro",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing American", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 10},
            {"exercise_name": "KB Thruster", "reps": 20},
        ],
    },
]
