# Curated starter set of "voorgedefinieerde workouts" (workout-ideeen), grouped by
# training_type so the frontend can offer an AMRAP / EMOM / Tabata / Anders (FOR_TIME)
# browse menu. Structures (rep schemes, time domains, movement combos) are based on
# well-established, publicly documented CrossFit programming patterns for each training
# type - not reproductions of specific named benchmark WODs (those live in fixed_wods.py).
# Every movement references an exercise name that must exist in seed/exercises.py; the
# seeder resolves these names to Exercise ids at insert time.
#
# rounds_override/rep_scheme_override are only read for training_type == "FOR_TIME" (see
# wod_generator._shape_predefined) - AMRAP/EMOM/TABATA derive their shape automatically.
PREDEFINED_WODS = [
    # --- AMRAP ---
    {
        "name": "Full Body Blast",
        "training_type": "AMRAP",
        "description": "Laagdrempelige full-body AMRAP om je conditie op te bouwen.",
        "duration_minutes": 12,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 15},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Sit-up", "reps": 15},
        ],
    },
    {
        "name": "Pull & Push Power",
        "training_type": "AMRAP",
        "description": "Bovenlichaam-AMRAP die trekkracht, duwkracht en een sprong combineert.",
        "duration_minutes": 15,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 8},
            {"exercise_name": "DB Shoulder Press", "reps": 10},
            {"exercise_name": "Box Jump", "reps": 12},
        ],
    },
    {
        "name": "Engine Builder",
        "training_type": "AMRAP",
        "description": "Hoog tempo AMRAP die kracht en conditie combineert.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 200},
        ],
    },
    {
        "name": "Heavy Metal",
        "training_type": "AMRAP",
        "description": "Zware AMRAP voor gevorderden met deadlifts en push press.",
        "duration_minutes": 20,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 10},
            {"exercise_name": "Push Press", "reps": 8},
            {"exercise_name": "Box Jump", "reps": 12},
        ],
    },
    {
        "name": "Endurance Grinder",
        "training_type": "AMRAP",
        "description": "Lange uithoudings-AMRAP met gymnastiek en een hardloopstuk.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    # --- Buddy WOD (1, AMRAP) - I-Go-You-Go format: one partner works a full round while
    # the other rests, then switches. See the FOR_TIME/EMOM sections below for the other two
    # partner formats (split-reps, synchro). is_buddy=True surfaces the "Buddy WOD"-filter/tag.
    {
        "name": "I-Go-You-Go Sprint",
        "training_type": "AMRAP",
        "description": "I-Go-You-Go: partner A doet 1 ronde, dan rust terwijl partner B dezelfde ronde doet. Wissel na elke ronde - samen zoveel mogelijk ronden in de tijd.",
        "duration_minutes": 20,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing American", "reps": 12},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Air Squat", "reps": 15},
        ],
    },
    # --- Reisvriendelijke WOD's (3) - geïnspireerd op crossfit.com/essentials/travel-workouts-
    # stay-fit-this-summer (alleen het format/de opzet, geen letterlijke overname - zelfde aanpak
    # als de rest van dit bestand: "based on well-established programming patterns", zie boven).
    # Puur bodyweight, dus overal te doen, geen apparatuur nodig.
    {
        "name": "Overal Fit",
        "training_type": "AMRAP",
        "description": "Korte, overal-te-doen AMRAP - geen apparatuur nodig, ideaal op reis of thuis.",
        "duration_minutes": 10,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 10},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "Push-up", "reps": 10},
        ],
    },
    # --- Long Hyrox-style AMRAPs (10) - user-supplied, 45 min multi-station chippers.
    # A few movements without a direct equivalent are substituted with the closest existing
    # exercise: Sandbag Carry -> DB/KB Farmers Carry (documented stand-in, see exercises.py),
    # Box Step-Up/Step-Over -> Box Step-Up. Ambiguous "Farmer Carry" (no DB/KB specified in the
    # source) is resolved per-WOD to whichever implement the rest of that WOD already uses.
    {
        "name": "Hyrox Engine Builder",
        "training_type": "AMRAP",
        "description": "Lange Hyrox-stijl AMRAP met skien, roeien en een dragende afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "DB Thruster", "reps": 12},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Grinder",
        "training_type": "AMRAP",
        "description": "Hyrox-stijl chipper met hardlopen, wall balls en een sled-achtige afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Full Body (Hyrox)",
        "training_type": "AMRAP",
        "description": "Lange full-body AMRAP met barbell, kettlebell en hardlopen.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 10},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
        ],
    },
    {
        "name": "Grip & Engine",
        "training_type": "AMRAP",
        "description": "Grip-intensieve AMRAP: skien, dragen en kettlebell-kracht.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Strong Legs",
        "training_type": "AMRAP",
        "description": "Lange beenintensieve AMRAP met hardlopen, lunges en wall balls.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 600},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 300},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Russian Twist", "reps": 20},
        ],
    },
    {
        "name": "Hybrid",
        "training_type": "AMRAP",
        "description": "Hybride AMRAP die skien, snatches en hardlopen combineert.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "calories": 20},
            {"exercise_name": "DB Snatch", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Long Engine",
        "training_type": "AMRAP",
        "description": "Uithoudings-chipper met een lange roeiafstand en tussenstops.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 1000},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Functional Fitness",
        "training_type": "AMRAP",
        "description": "Klassieke Hyrox-stijl functionele AMRAP met thrusters en wall balls.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Style",
        "training_type": "AMRAP",
        "description": "Lange Hyrox-stijl AMRAP met hardlopen, wall balls en burpee broad jumps.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 25},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Endurance Chipper",
        "training_type": "AMRAP",
        "description": "Lange uithoudings-AMRAP met barbell, pull-ups en een dragende afstand.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    # --- EMOM ---
    {
        "name": "Quick Starter",
        "training_type": "EMOM",
        "description": "Korte EMOM om kennis te maken met roterende oefeningen op de minuut.",
        "duration_minutes": 10,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 12},
            {"exercise_name": "Push-up", "reps": 10},
        ],
    },
    {
        "name": "Total Body Rotation",
        "training_type": "EMOM",
        "description": "EMOM die het hele lichaam laat roteren langs vier oefeningen.",
        "duration_minutes": 16,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 10},
            {"exercise_name": "Row", "calories": 12},
            {"exercise_name": "Sit-up", "reps": 15},
            {"exercise_name": "Box Jump", "reps": 10},
        ],
    },
    {
        "name": "Strength & Sweat",
        "training_type": "EMOM",
        "description": "Combineert een zware kniebuiging met conditiewerk op de minuut.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Back Squat", "reps": 5},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "KB Swing American", "reps": 12},
            {"exercise_name": "Double Unders", "reps": 20},
        ],
    },
    {
        "name": "Barbell Cycling",
        "training_type": "EMOM",
        "description": "Technische barbell-EMOM voor gevorderden: clean, squat en jerk.",
        "duration_minutes": 12,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Power Clean", "reps": 5},
            {"exercise_name": "Front Squat", "reps": 5},
            {"exercise_name": "Push Jerk", "reps": 5},
        ],
    },
    {
        "name": "Cardio Rotation",
        "training_type": "EMOM",
        "description": "Lange EMOM die cardiomachines afwisselt met kracht en gymnastiek.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 12},
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 8},
            {"exercise_name": "KB Clean", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    # --- Buddy WOD (1, EMOM) - alternating-minute format, the EMOM equivalent of I-Go-You-Go.
    {
        "name": "Buddy EMOM Engine",
        "training_type": "EMOM",
        "description": "EMOM om en om: in de oneven minuten werkt partner A, in de even minuten partner B - ieder je eigen oefening, samen 1 blok.",
        "duration_minutes": 16,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 12},
        ],
    },
    # --- TABATA ---
    {
        "name": "Tabata Classics",
        "training_type": "TABATA",
        "description": "De klassieke Tabata-combinatie: benen, borst en buik.",
        "duration_minutes": 16,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat"},
            {"exercise_name": "Push-up"},
            {"exercise_name": "Sit-up"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    {
        "name": "Kettlebell Tabata",
        "training_type": "TABATA",
        "description": "Korte, pittige Tabata met kettlebell-oefeningen.",
        "duration_minutes": 8,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "KB Swing Russian"},
            {"exercise_name": "Goblet Squat"},
        ],
    },
    {
        "name": "Engine Tabata",
        "training_type": "TABATA",
        "description": "Tabata gericht op conditie en core.",
        "duration_minutes": 12,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Burpee"},
            {"exercise_name": "Double Unders"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    {
        "name": "Upper Body Tabata",
        "training_type": "TABATA",
        "description": "Tabata die focust op borst, triceps en schouders.",
        "duration_minutes": 16,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Push-up"},
            {"exercise_name": "Ring Dip"},
            {"exercise_name": "Pike Push-up"},
            {"exercise_name": "DB Shoulder Press"},
        ],
    },
    {
        "name": "Full Send Tabata",
        "training_type": "TABATA",
        "description": "Vijf zware oefeningen kort na elkaar - een pittige conditietest.",
        "duration_minutes": 20,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Wall Ball Shot"},
            {"exercise_name": "Box Jump"},
            {"exercise_name": "KB Swing American"},
            {"exercise_name": "Burpee"},
            {"exercise_name": "Mountain Climbers"},
        ],
    },
    # --- FOR_TIME ("Anders") ---
    {
        "name": "Classic Triplet",
        "training_type": "FOR_TIME",
        "description": "Klassiek dalend schema: 21-15-9 van twee oefeningen, zo snel mogelijk.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "3",
        "rep_scheme_override": "21-15-9",
        "movements": [
            {"exercise_name": "Thruster", "reps": 21},
            {"exercise_name": "Kipping Pull-up", "reps": 21},
        ],
    },
    {
        "name": "Chipper Challenge",
        "training_type": "FOR_TIME",
        "description": "Vijf oefeningen in aflopende reeks - werk je van veel naar weinig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend",
        "movements": [
            {"exercise_name": "Double Unders", "reps": 50},
            {"exercise_name": "Wall Ball Shot", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Burpee", "reps": 10},
        ],
    },
    {
        "name": "Deadlift Domination",
        "training_type": "FOR_TIME",
        "description": "Zwaar 21-15-9-schema met deadlifts en burpees.",
        "duration_minutes": 10,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "21-15-9",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 21},
            {"exercise_name": "Burpee", "reps": 21},
        ],
    },
    {
        "name": "Row & Grind",
        "training_type": "FOR_TIME",
        "description": "Rechttoe-rechtaan for-time workout met roeien en kracht.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Wall Ball Shot", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 40},
        ],
    },
    {
        "name": "The Ladder",
        "training_type": "FOR_TIME",
        "description": "Oplopende ladder tot 10 - hoe verder, hoe zwaarder.",
        "duration_minutes": 18,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "oplopende ladder 2-4-6-8-10",
        "movements": [
            {"exercise_name": "DB Snatch", "reps": 10},
            {"exercise_name": "Box Jump", "reps": 10},
        ],
    },
    # --- Buddy WODs (2, FOR_TIME) - split-reps and synchro, the other two partner formats
    # (see "I-Go-You-Go Sprint" above for the alternating one).
    {
        "name": "Buddy Chipper",
        "training_type": "FOR_TIME",
        "description": "Partner-chipper: verdeel de reps onderling zoals jullie willen, samen optellen tot het totaal hieronder. Ideaal om samen met een buddy te doen.",
        "duration_minutes": 25,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend, samen verdelen",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 80},
            {"exercise_name": "Box Jump", "reps": 60},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
            {"exercise_name": "Burpee", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
        ],
    },
    {
        "name": "Synchro Squat & Row",
        "training_type": "FOR_TIME",
        "description": "Synchro: voer de kniebuigingen tegelijk met je buddy uit - een rep telt pas als jullie gelijk zijn. Bij het roeien wissel je om de beurt af.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "synchro krachtdeel + afwisselend cardio",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Goblet Squat", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
    # --- Reisvriendelijke WOD's, vervolg (2, FOR_TIME) - zie de AMRAP-sectie hierboven voor de
    # bron/aanpak-toelichting.
    {
        "name": "Thuis Chipper",
        "training_type": "FOR_TIME",
        "description": "Aflopende chipper zonder apparatuur - overal te doen, ook op reis.",
        "duration_minutes": 18,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend 60-50-40-30-20",
        "movements": [
            {"exercise_name": "Sit-up", "reps": 60},
            {"exercise_name": "Walking Lunge", "reps": 50},
            {"exercise_name": "Push-up", "reps": 40},
            {"exercise_name": "Bodyweight Good Morning", "reps": 30},
            {"exercise_name": "Burpee", "reps": 20},
        ],
    },
    {
        "name": "Hardloop & Burpees",
        "training_type": "FOR_TIME",
        "description": "3 ronden hardlopen en burpee broad jumps - simpel op te bouwen, overal en altijd te doen zolang je buiten kunt hardlopen.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "3",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    # --- Buddy WODs, vervolg (2, FOR_TIME) - geïnspireerd op echte partner-WOD's van
    # outdoormusclefit.com/partner-crossfit-workouts (format/opzet, geen letterlijke overname -
    # zelfde aanpak als de rest van dit bestand). "Buffalo 10" introduceert een 4e partnerformaat
    # naast I-Go-You-Go/split-reps/synchro: station-rotatie, waarbij je samen door dezelfde
    # oefeningen roteert (na elke oefening van plek wisselen) i.p.v. samen te werken op 1 oefening.
    {
        "name": "Buffalo 10",
        "training_type": "FOR_TIME",
        "description": "Station-rotatie: na elke oefening wissel je met je buddy van plek. Het hardloopstuk doe je samen.",
        "duration_minutes": 30,
        "level": "intermediate",
        "rounds_override": "10",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Deadlift", "reps": 5},
            {"exercise_name": "Push-up", "reps": 14},
            {"exercise_name": "Double Unders", "reps": 22},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Pulse",
        "training_type": "FOR_TIME",
        "description": "Synchro: de burpees doe je gelijktijdig met je buddy - een rep telt pas als jullie gelijk zijn. De rest van de ronde en het hardloopstuk doe je om de beurt.",
        "duration_minutes": 25,
        "level": "advanced",
        "rounds_override": "6",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Burpee", "reps": 12},
            {"exercise_name": "KB Swing Russian", "reps": 16},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },

    # --- Reisvriendelijke WOD's, aanvulling 2 (4) - crossfit.com/essentials/travel-workouts
    # bevat in totaal maar 9 workouts (geen paginering/verborgen content - dubbel-gecheckt).
    # 3 daarvan staan al hierboven; dit zijn de overige bruikbare (2 pasten niet goed: een sets-
    # met-rust-interval-format past niet op AMRAP/EMOM/FOR_TIME, en 1 was te dun als losstaand
    # idee). "Plank Up-Down" is nieuw toegevoegd aan exercises.py voor #4 hieronder.
    {
        "name": "Sprint & Plank",
        "training_type": "AMRAP",
        "description": "Cardio en core afwisselend - overal te doen, alleen wat ruimte om te rennen nodig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Plank Up-Down", "reps": 20},
        ],
    },
    {
        "name": "Bodyweight EMOM",
        "training_type": "EMOM",
        "description": "Wisselende bodyweight-oefening elke minuut - geen apparatuur nodig.",
        "duration_minutes": 20,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 12},
            {"exercise_name": "Burpee", "reps": 12},
            {"exercise_name": "Pike Push-up", "reps": 12},
            {"exercise_name": "V-up", "reps": 12},
        ],
    },
    {
        "name": "Deadlift & Core AMRAP",
        "training_type": "AMRAP",
        "description": "Combinatie van kracht en core - werkt met een halterstang of een zwaar object (bijv. een volle tas) als je thuis geen gewichten hebt.",
        "duration_minutes": 15,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Deadlift", "reps": 10},
            {"exercise_name": "V-up", "reps": 15},
            {"exercise_name": "Air Squat", "reps": 15},
        ],
    },

    # --- Buddy WODs, aanvulling (19) - outdoormusclefit.com/partner-crossfit-workouts bevat 50
    # partner-WOD's; dit is een selectie die goed past bij de bestaande oefeningen-catalogus,
    # met gematigder volume dan de originele (vaak extreme) hero-WOD-achtige aantallen - passend
    # bij dit project se "simpel en toegankelijk" uitgangspunt. Formaat/opzet overgenomen, geen
    # letterlijke tekst. "Save Connor" introduceert een 5e partnerformaat: concurrent-verschillend-
    # werk (partners doen tegelijk andere oefeningen, wisselen na een ronde) naast I-Go-You-Go/
    # split-reps/synchro/station-rotatie.
    {
        "name": "Howdy Partner",
        "training_type": "FOR_TIME",
        "description": "Samen op de Airbike, verdeel de Rope Climbs en Deadlifts onderling.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Rope Climb", "reps": 6},
            {"exercise_name": "Deadlift", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Eva Strong",
        "training_type": "FOR_TIME",
        "description": "Double-unders samen, Toes-to-Bar en Clean and Jerk verdeel je onderling.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Double Unders", "reps": 24},
            {"exercise_name": "Toes-to-Bar", "reps": 15},
            {"exercise_name": "Clean and Jerk", "reps": 2},
        ],
    },
    {
        "name": "Friendly Murph",
        "training_type": "FOR_TIME",
        "description": "Partner-versie van Murph: verdeel de pull-ups, push-ups en squats onderling zoals jullie willen. Het hardlopen doe je samen.",
        "duration_minutes": 45,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "samen verdelen",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1600},
            {"exercise_name": "Kipping Pull-up", "reps": 100},
            {"exercise_name": "Push-up", "reps": 200},
            {"exercise_name": "Air Squat", "reps": 300},
            {"exercise_name": "Running", "distance_meters": 1600},
        ],
    },
    {
        "name": "Barbell Bros",
        "training_type": "FOR_TIME",
        "description": "Verdeel de barbell-reps zoals jullie willen. Het hardlopen doe je samen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1600},
            {"exercise_name": "Front Squat", "reps": 50},
            {"exercise_name": "Push Jerk", "reps": 30},
            {"exercise_name": "Walking Lunge", "reps": 30},
        ],
    },
    {
        "name": "Miller",
        "training_type": "FOR_TIME",
        "description": "I-Go-You-Go: wissel elke ronde af met je buddy.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "10",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "DB Walking Lunge", "reps": 14},
        ],
    },
    {
        "name": "Hannah",
        "training_type": "FOR_TIME",
        "description": "Verdeel de ronden met je buddy. Sluit samen af met de hardloop-cash-out.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "8",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Burpee Box Jump Over", "reps": 7},
            {"exercise_name": "Running", "distance_meters": 2000},
        ],
    },
    {
        "name": "Save Connor",
        "training_type": "FOR_TIME",
        "description": "Concurrent: terwijl partner A rent, doet partner B tegelijk het krachtblok. Wissel na elke ronde.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "6",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 600},
            {"exercise_name": "DB Romanian Deadlift", "reps": 12},
            {"exercise_name": "KB Swing Russian", "reps": 12},
            {"exercise_name": "DB Thruster", "reps": 12},
        ],
    },
    {
        "name": "Cash",
        "training_type": "AMRAP",
        "description": "Samen zoveel mogelijk ronden - werk of wissel af zoals jullie willen.",
        "duration_minutes": 20,
        "level": "intermediate",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
        ],
    },
    {
        "name": "Ares",
        "training_type": "AMRAP",
        "description": "Samen zoveel mogelijk ronden - werk of wissel af zoals jullie willen.",
        "duration_minutes": 16,
        "level": "advanced",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 15},
            {"exercise_name": "GHD Sit-up", "reps": 12},
            {"exercise_name": "Box Jump Over", "reps": 10},
        ],
    },
    {
        "name": "TWR Pride WOD",
        "training_type": "AMRAP",
        "description": "De burpees doe je synchroon met je buddy. De rest van de ronde doe je om de beurt.",
        "duration_minutes": 20,
        "level": "advanced",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Squat Clean", "reps": 6},
            {"exercise_name": "Burpee", "reps": 6},
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "DB Snatch", "reps": 14},
        ],
    },
    {
        "name": "Barber Pole",
        "training_type": "FOR_TIME",
        "description": "I-Go-You-Go op één oefening: wissel elke 25 cal met je buddy.",
        "duration_minutes": 8,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 25},
        ],
    },
    {
        "name": "CBC Qualifier 21.2",
        "training_type": "FOR_TIME",
        "description": "Verdeel de reps met je buddy zoals jullie willen.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Front Squat", "reps": 15},
            {"exercise_name": "Toes-to-Bar", "reps": 30},
            {"exercise_name": "Thruster", "reps": 15},
        ],
    },
    {
        "name": "Noah Calderon",
        "training_type": "FOR_TIME",
        "description": "Verdeel de ronden met je buddy zoals jullie willen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "8",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Deadlift", "reps": 3},
            {"exercise_name": "KB Swing Russian", "reps": 8},
            {"exercise_name": "Box Jump", "reps": 12},
            {"exercise_name": "Burpee", "reps": 20},
        ],
    },
    {
        "name": "Honey Badger",
        "training_type": "AMRAP",
        "description": "Samen zoveel mogelijk ronden. Het hardlopen doe je samen.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Squat Clean", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Running", "distance_meters": 800},
        ],
    },
    {
        "name": "Taylor 91",
        "training_type": "FOR_TIME",
        "description": "Verdeel de reps met je buddy zoals jullie willen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 30},
            {"exercise_name": "Overhead Press", "reps": 30},
            {"exercise_name": "Front Squat", "reps": 30},
            {"exercise_name": "Burpee", "reps": 30},
        ],
    },
    {
        "name": "Uplift",
        "training_type": "FOR_TIME",
        "description": "Grote chipper - verdeel de reps met je buddy zoals jullie willen. Roeien doe je samen.",
        "duration_minutes": 30,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Squat Clean", "reps": 10},
            {"exercise_name": "Row", "distance_meters": 1800},
            {"exercise_name": "Double Unders", "reps": 100},
            {"exercise_name": "Burpee", "reps": 40},
            {"exercise_name": "Deadlift", "reps": 30},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
        ],
    },
    {
        "name": "We Remember",
        "training_type": "FOR_TIME",
        "description": "Terwijl de een klimt, houdt de ander een Plank Hold vol - wissel af tot het klimmen klaar is. Het hardlopen doe je samen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Rope Climb", "reps": 9},
            {"exercise_name": "Running", "distance_meters": 1600},
        ],
    },
    {
        "name": "Muhammad Ali",
        "training_type": "FOR_TIME",
        "description": "Verdeel de reps met je buddy zoals jullie willen. Het hardlopen doe je samen.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "Clean and Jerk", "reps": 20},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Toes-to-Bar", "reps": 20},
        ],
    },
    {
        "name": "Move Forward",
        "training_type": "FOR_TIME",
        "description": "Synchro: elke oefening doe je gelijktijdig met je buddy - een rep telt pas als jullie gelijk zijn.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "4",
        "rep_scheme_override": "synchro",
        "is_buddy": True,
        "movements": [
            {"exercise_name": "KB Swing American", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 10},
            {"exercise_name": "KB Thruster", "reps": 20},
        ],
    },

    # --- Thuis-WOD's, eigen samenstelling (9) - crossfit.com's travel-workouts-artikel had er
    # zelf maar 9 in totaal (6 daarvan al eerder toegevoegd, zie de "Reisvriendelijke WOD's"-
    # secties hierboven); dit zijn extra, zelf samengestelde workouts om de thuis-categorie
    # breder te maken, op dezelfde manier opgebouwd als de rest van dit bestand (bestaande
    # oefeningen, realistische volumes) maar niet van die bron overgenomen. Alle bewegingen zijn
    # requires_gym=False, dus deze krijgen automatisch de "Ook thuis"-tag.
    {
        "name": "Volledig Lichaam Bodyweight",
        "training_type": "AMRAP",
        "description": "Simpele full-body AMRAP zonder apparatuur.",
        "duration_minutes": 15,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 15},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Sit-up", "reps": 15},
            {"exercise_name": "Superman", "reps": 10},
        ],
    },
    {
        "name": "Core Blast Thuis",
        "training_type": "AMRAP",
        "description": "Buikspier-AMRAP, geen apparatuur nodig.",
        "duration_minutes": 12,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "V-up", "reps": 15},
            {"exercise_name": "Russian Twist", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
        ],
    },
    {
        "name": "Beenkracht Zonder Gewicht",
        "training_type": "FOR_TIME",
        "description": "Beenwerk met alleen je eigen lichaamsgewicht.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "4",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Reverse Lunge", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 20},
        ],
    },
    {
        "name": "Push Pull Thuis",
        "training_type": "EMOM",
        "description": "Afwisselend duwen en trekken, elke minuut een andere oefening.",
        "duration_minutes": 16,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Push-up", "reps": 12},
            {"exercise_name": "Superman", "reps": 12},
            {"exercise_name": "Diamond Push-up", "reps": 8},
            {"exercise_name": "Bird Dog", "reps": 12},
        ],
    },
    {
        "name": "Glutes & Core",
        "training_type": "AMRAP",
        "description": "Billen en buik, laagdrempelig en zonder apparatuur.",
        "duration_minutes": 12,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Glute Bridge", "reps": 15},
            {"exercise_name": "Donkey Kicks", "reps": 12},
            {"exercise_name": "Fire Hydrants", "reps": 12},
            {"exercise_name": "Sit-up", "reps": 15},
        ],
    },
    {
        "name": "Upper Body Bodyweight Chipper",
        "training_type": "FOR_TIME",
        "description": "Aflopende chipper voor je bovenlichaam, geen apparatuur nodig.",
        "duration_minutes": 15,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend 40-30-20-10",
        "movements": [
            {"exercise_name": "Push-up", "reps": 40},
            {"exercise_name": "Tricep Dips", "reps": 30},
            {"exercise_name": "Wide Push-up", "reps": 20},
            {"exercise_name": "Diamond Push-up", "reps": 10},
        ],
    },
    {
        "name": "Tabata Thuis",
        "training_type": "TABATA",
        "description": "Klassieke Tabata zonder apparatuur - benen en borst.",
        "duration_minutes": 8,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat"},
            {"exercise_name": "Push-up"},
        ],
    },
    {
        "name": "Handstand Progressie",
        "training_type": "FOR_TIME",
        "description": "Gymnastiek-skills combineren met conditie, geen apparatuur nodig.",
        "duration_minutes": 15,
        "level": "advanced",
        "rounds_override": "3",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Handstand Push-up", "reps": 5},
            {"exercise_name": "Pistol Squat", "reps": 6},
            {"exercise_name": "Burpee", "reps": 10},
        ],
    },
    {
        "name": "Ochtend Bodyweight Flow",
        "training_type": "AMRAP",
        "description": "Korte, rustige AMRAP om de dag mee te beginnen - geen apparatuur nodig.",
        "duration_minutes": 10,
        "level": "beginner",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 10},
            {"exercise_name": "Incline Push-up", "reps": 10},
            {"exercise_name": "Superman", "reps": 10},
            {"exercise_name": "Bird Dog", "reps": 10},
        ],
    },

    # --- For Time chippers (17) - user-supplied batch. Sandbag-only movements substitute
    # DB/KB equivalents per this file's existing convention (see exercises.py's top comment):
    # Sandbag Squat -> DB Sumo Squat, Sandbag Over Shoulder -> DB Clean, Sandbag/Bear Hug
    # Carry -> DB/KB Farmers Carry. Three names collided with existing entries and got a
    # "Chipper" suffix to disambiguate: Hyrox Style, Engine Builder, Row & Grind.
    {
        "name": "The Classic",
        "training_type": "FOR_TIME",
        "description": "Klassieke chipper met hardlopen, wall balls, kettlebell swings en pull-ups.",
        "duration_minutes": 20,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
            {"exercise_name": "KB Swing Russian", "reps": 40},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Full Body Chipper",
        "training_type": "FOR_TIME",
        "description": "Full-body chipper met roeien, squats en overhead-werk.",
        "duration_minutes": 20,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Goblet Squat", "reps": 40},
            {"exercise_name": "Box Jump Over", "reps": 30},
            {"exercise_name": "Ground to Overhead", "reps": 20},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "Ski Erg", "distance_meters": 500},
        ],
    },
    {
        "name": "Hyrox Style Chipper",
        "training_type": "FOR_TIME",
        "description": "Hyrox-geïnspireerde chipper met hardlopen, lunges en wall balls. Sandbag carry vervangen door dumbbell farmers carry.",
        "duration_minutes": 28,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1000},
            {"exercise_name": "Walking Lunge", "reps": 50},
            {"exercise_name": "Wall Ball Shot", "reps": 40},
            {"exercise_name": "Burpee Broad Jump", "reps": 30},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Grip Killer",
        "training_type": "FOR_TIME",
        "description": "Grip-intensieve chipper met pull-ups, kettlebell swings en een farmers carry.",
        "duration_minutes": 17,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 30},
            {"exercise_name": "KB Swing Russian", "reps": 40},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Row", "distance_meters": 500},
        ],
    },
    {
        "name": "Long Burner",
        "training_type": "FOR_TIME",
        "description": "Langere chipper die conditie en volume combineert.",
        "duration_minutes": 26,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 1000},
            {"exercise_name": "Air Squat", "reps": 50},
            {"exercise_name": "Sit-up", "reps": 40},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 800},
        ],
    },
    {
        "name": "Sandbag Special",
        "training_type": "FOR_TIME",
        "description": "Functionele chipper geïnspireerd op sandbag-werk - hier met dumbbell/kettlebell-varianten.",
        "duration_minutes": 22,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "DB Sumo Squat", "reps": 50},
            {"exercise_name": "DB Clean", "reps": 30},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Walking Lunge", "reps": 40},
            {"exercise_name": "Row", "distance_meters": 500},
        ],
    },
    {
        "name": "Engine Builder Chipper",
        "training_type": "FOR_TIME",
        "description": "Explosieve chipper met hardlopen, wall balls en thrusters.",
        "duration_minutes": 20,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "Wall Ball Shot", "reps": 40},
            {"exercise_name": "Goblet Squat", "reps": 30},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "Ski Erg", "distance_meters": 500},
        ],
    },
    {
        "name": "CrossFit Open Style",
        "training_type": "FOR_TIME",
        "description": "Chipper in de stijl van een CrossFit Open-workout - veel volume, aflopend in reps.",
        "duration_minutes": 24,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend",
        "movements": [
            {"exercise_name": "Box Jump Over", "reps": 50},
            {"exercise_name": "Push-up", "reps": 40},
            {"exercise_name": "Kipping Pull-up", "reps": 30},
            {"exercise_name": "Ground to Overhead", "reps": 20},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 800},
        ],
    },
    {
        "name": "The Carry",
        "training_type": "FOR_TIME",
        "description": "Chipper met veel dragen en grip-werk.",
        "duration_minutes": 18,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 200},
            {"exercise_name": "KB Swing Russian", "reps": 40},
            {"exercise_name": "Walking Lunge", "reps": 30},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Row & Grind Chipper",
        "training_type": "FOR_TIME",
        "description": "Rechttoe-rechtaan chipper met roeien, wall balls en lunges.",
        "duration_minutes": 20,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 1000},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
            {"exercise_name": "Walking Lunge", "reps": 40},
            {"exercise_name": "Sit-up", "reps": 30},
            {"exercise_name": "Burpee", "reps": 20},
        ],
    },
    {
        "name": "Descending Ladder",
        "training_type": "FOR_TIME",
        "description": "Aflopende ladder van 50 naar 10, afgesloten met een lange run.",
        "duration_minutes": 22,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "aflopend 50-40-30-20-10",
        "movements": [
            {"exercise_name": "Air Squat", "reps": 50},
            {"exercise_name": "KB Swing Russian", "reps": 40},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "Thruster", "reps": 10},
            {"exercise_name": "Running", "distance_meters": 1000},
        ],
    },
    {
        "name": "Upper Body Chipper",
        "training_type": "FOR_TIME",
        "description": "Bovenlichaam-chipper met pull-ups, push-ups, push press en renegade rows.",
        "duration_minutes": 18,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 30},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Push Press", "reps": 30},
            {"exercise_name": "DB Renegade Row", "reps": 30},
            {"exercise_name": "Ski Erg", "calories": 30},
        ],
    },
    {
        "name": "Leg Day",
        "training_type": "FOR_TIME",
        "description": "Beenintensieve chipper met lunges, squats en step-ups.",
        "duration_minutes": 24,
        "level": "intermediate",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Walking Lunge", "reps": 100},
            {"exercise_name": "Goblet Squat", "reps": 50},
            {"exercise_name": "Box Step-Up", "reps": 40},
            {"exercise_name": "Wall Ball Shot", "reps": 30},
            {"exercise_name": "Running", "distance_meters": 800},
        ],
    },
    {
        "name": "Total Body Chipper",
        "training_type": "FOR_TIME",
        "description": "Full-body chipper die kracht, grip en conditie combineert.",
        "duration_minutes": 26,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Ground to Overhead", "reps": 30},
            {"exercise_name": "KB Swing Russian", "reps": 40},
            {"exercise_name": "Push-up", "reps": 30},
            {"exercise_name": "Kipping Pull-up", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Hyrox Finisher",
        "training_type": "FOR_TIME",
        "description": "Zware afsluitende Hyrox-stijl chipper. Sandbag over shoulder vervangen door DB clean.",
        "duration_minutes": 26,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1000},
            {"exercise_name": "Wall Ball Shot", "reps": 50},
            {"exercise_name": "Burpee Broad Jump", "reps": 40},
            {"exercise_name": "Walking Lunge", "reps": 30},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Clean", "reps": 10},
        ],
    },
    {
        "name": "Iron Man Chipper",
        "training_type": "FOR_TIME",
        "description": "Hero-chipper: lange, zware for-time workout over bijna alle bewegingspatronen.",
        "duration_minutes": 40,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 1000},
            {"exercise_name": "Air Squat", "reps": 100},
            {"exercise_name": "Wall Ball Shot", "reps": 75},
            {"exercise_name": "Push-up", "reps": 50},
            {"exercise_name": "Kipping Pull-up", "reps": 40},
            {"exercise_name": "Ground to Overhead", "reps": 30},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Row", "distance_meters": 1000},
        ],
    },
    {
        "name": "The Furnace",
        "training_type": "FOR_TIME",
        "description": "Hero-chipper met veel volume op de SkiErg, lunges en kettlebell swings.",
        "duration_minutes": 38,
        "level": "advanced",
        "rounds_override": "1",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 2000},
            {"exercise_name": "Walking Lunge", "reps": 100},
            {"exercise_name": "KB Swing Russian", "reps": 80},
            {"exercise_name": "Box Jump Over", "reps": 60},
            {"exercise_name": "Kipping Pull-up", "reps": 40},
            {"exercise_name": "Devil Press", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 800},
        ],
    },

    # --- Power (24) - user-supplied batch, kracht-gerichte/muscle-group-tied WOD's, tagged
    # is_power=True (curated, like is_buddy - not derivable from movements the way is_hyrox
    # is). Same sandbag-substitution convention as the chipper batch above (see that comment).
    # "Grip Killer" was renamed "Grip Killer Power" - collided with the FOR_TIME chipper of the
    # same name added earlier. Per-set weights the user specified (e.g. "24 kg", "2x15 kg")
    # aren't representable in PredefinedWodMovement (no weight field) - mentioned in the
    # description instead.
    {
        "name": "Leg Destroyer",
        "training_type": "FOR_TIME",
        "description": "Beenintensieve krachtworkout - 24 kg goblet squats, 2x15 kg walking lunges.",
        "duration_minutes": 28,
        "level": "advanced",
        "is_power": True,
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Box Jump", "reps": 15},
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
    {
        "name": "Push Day",
        "training_type": "AMRAP",
        "description": "Duwkracht-AMRAP: thrusters, push press en burpees.",
        "duration_minutes": 25,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "DB Thruster", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 15},
        ],
    },
    {
        "name": "Pull & Grip",
        "training_type": "EMOM",
        "description": "Grip-EMOM: pull-ups, farmers carry en renegade rows roteren elke minuut, 10 ronden.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 10},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "DB Renegade Row", "reps": 15},
        ],
    },
    {
        "name": "Full Body Strength",
        "training_type": "FOR_TIME",
        "description": "Zware full-body krachtworkout in 5 ronden.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Legs & Core",
        "training_type": "AMRAP",
        "description": "Benen- en buikgerichte AMRAP.",
        "duration_minutes": 30,
        "level": "intermediate",
        "is_power": True,
        "movements": [
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Burpee", "reps": 15},
        ],
    },
    {
        "name": "Shoulder Burner",
        "training_type": "FOR_TIME",
        "description": "Schouderintensieve workout met push press, thrusters en pike push-ups.",
        "duration_minutes": 22,
        "level": "advanced",
        "is_power": True,
        "rounds_override": "4",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Pike Push-up", "reps": 15},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
        ],
    },
    {
        "name": "Hyrox Power",
        "training_type": "AMRAP",
        "description": "Hyrox-stijl kracht-AMRAP. Sandbag lunges vervangen door walking lunges.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "Wall Ball Shot", "reps": 25},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Posterior Chain",
        "training_type": "FOR_TIME",
        "description": "Focus op de achterste keten: kettlebell swings en romanian deadlifts.",
        "duration_minutes": 24,
        "level": "intermediate",
        "is_power": True,
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "DB Romanian Deadlift", "reps": 15},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 300},
        ],
    },
    {
        "name": "Chest & Arms",
        "training_type": "AMRAP",
        "description": "Borst- en armgerichte AMRAP met dips en pull-ups.",
        "duration_minutes": 25,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Ring Dip", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Strong Engine",
        "training_type": "FOR_TIME",
        "description": "Kracht en conditie in 6 korte, zware ronden.",
        "duration_minutes": 22,
        "level": "advanced",
        "is_power": True,
        "rounds_override": "6",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 250},
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 10},
            {"exercise_name": "Burpee", "reps": 10},
        ],
    },
    {
        "name": "Sandbag Beast",
        "training_type": "FOR_TIME",
        "description": "Functionele krachtworkout - sandbag-bewegingen vervangen door dumbbell/kettlebell-varianten.",
        "duration_minutes": 22,
        "level": "advanced",
        "is_power": True,
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "DB Clean", "reps": 15},
            {"exercise_name": "DB Sumo Squat", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Burpee", "reps": 15},
        ],
    },
    {
        "name": "Grip Killer Power",
        "training_type": "AMRAP",
        "description": "Grip-intensieve kracht-AMRAP met swings, carry en renegade rows.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "DB Renegade Row", "reps": 15},
            {"exercise_name": "Sit-up", "reps": 20},
        ],
    },
    {
        "name": "Sprint Intervals",
        "training_type": "FOR_TIME",
        "description": "10 korte sprint-ronden met 30 sec rust ertussen.",
        "duration_minutes": 20,
        "level": "intermediate",
        "is_power": True,
        "rounds_override": "10",
        "rep_scheme_override": "10 ronden, 30 sec rust ertussen",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 200},
            {"exercise_name": "Push-up", "reps": 15},
            {"exercise_name": "Goblet Squat", "reps": 15},
        ],
    },
    {
        "name": "Quad Attack",
        "training_type": "FOR_TIME",
        "description": "Beenintensieve workout met wall balls, lunges en step-ups.",
        "duration_minutes": 24,
        "level": "intermediate",
        "is_power": True,
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
    {
        "name": "Upper Body Engine",
        "training_type": "AMRAP",
        "description": "Bovenlichaam-kracht-AMRAP met pull-ups en push press.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Full Body EMOM",
        "training_type": "EMOM",
        "description": "Zware full-body EMOM, 6 ronden van 5 oefeningen.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Thruster", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 15},
            {"exercise_name": "Kipping Pull-up", "reps": 12},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Heavy Carry",
        "training_type": "AMRAP",
        "description": "Zware carry-AMRAP gecombineerd met squats, push-ups en pull-ups.",
        "duration_minutes": 25,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "DB Farmers Carry", "distance_meters": 150},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
        ],
    },
    {
        "name": "Conditioning",
        "training_type": "FOR_TIME",
        "description": "Simpele maar zware conditie-workout: hardlopen, wall balls, burpees.",
        "duration_minutes": 24,
        "level": "advanced",
        "is_power": True,
        "rounds_override": "5",
        "rep_scheme_override": "flat",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
        ],
    },
    {
        "name": "Hyrox Sprint",
        "training_type": "AMRAP",
        "description": "Hyrox-stijl sprint-AMRAP.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Total Body Power",
        "training_type": "AMRAP",
        "description": "Full-body kracht-AMRAP.",
        "duration_minutes": 30,
        "level": "advanced",
        "is_power": True,
        "movements": [
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Box Jump Over", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },

    # --- Power finishers (4) - de korte AMRAP-afsluiters uit de "Bodybuilding meets CrossFit"
    # combinatie. Het krachtblok ervoor (bijv. 4x12 DB Bench Press) is traditionele sets-x-reps
    # bodybuilding-programmering, die dit datamodel niet kent (geen "sets"-veld) - alleen de
    # AMRAP-finisher is dus als losse WOD toegevoegd, met het krachtblok in de omschrijving.
    {
        "name": "Chest Day Finisher",
        "training_type": "AMRAP",
        "description": "Korte AMRAP-afsluiter voor chest day. Ga eraan vooraf met bijv. 4x12 DB Bench Press en 4x15 Incline Push-ups.",
        "duration_minutes": 15,
        "level": "intermediate",
        "is_power": True,
        "movements": [
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "Push-up", "reps": 10},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
    {
        "name": "Back Day Finisher",
        "training_type": "AMRAP",
        "description": "Korte AMRAP-afsluiter voor back day. Ga eraan vooraf met bijv. 5x8 Pull-ups en 4x12 DB Bent-over Row.",
        "duration_minutes": 15,
        "level": "intermediate",
        "is_power": True,
        "movements": [
            {"exercise_name": "Kipping Pull-up", "reps": 10},
            {"exercise_name": "KB Swing Russian", "reps": 15},
            {"exercise_name": "Running", "distance_meters": 200},
        ],
    },
    {
        "name": "Leg Day Finisher",
        "training_type": "AMRAP",
        "description": "Korte AMRAP-afsluiter voor leg day. Ga eraan vooraf met bijv. 5x10 Front Squat of Goblet Squat en 4x20 Walking Lunges.",
        "duration_minutes": 15,
        "level": "intermediate",
        "is_power": True,
        "movements": [
            {"exercise_name": "Box Jump", "reps": 15},
            {"exercise_name": "Wall Ball Shot", "reps": 15},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
        ],
    },
    {
        "name": "Shoulder Day Finisher",
        "training_type": "AMRAP",
        "description": "Korte AMRAP-afsluiter voor shoulder day. Ga eraan vooraf met bijv. 5x10 Push Press en 4x12 DB Lateral Raise.",
        "duration_minutes": 15,
        "level": "intermediate",
        "is_power": True,
        "movements": [
            {"exercise_name": "Thruster", "reps": 10},
            {"exercise_name": "Burpee", "reps": 10},
            {"exercise_name": "Assault Bike", "calories": 12},
        ],
    },

    # --- Extra AMRAPs (20) - user-supplied batch (WOD 11-30), mixed-modal conditioning, not
    # tagged is_power (unlike the Power batch above, these aren't tied to a specific muscle
    # group - the user introduced them separately as generic AMRAPs). Only WOD 11 had an
    # explicit duration ("45 min AMRAP") - the rest are estimated from volume. Sandbag
    # movements substitute DB/KB equivalents per the existing convention (see exercises.py).
    # Two names collided with earlier chipper additions (Long Burner, Hyrox Finisher) and got
    # an "AMRAP" suffix to disambiguate.
    {
        "name": "Cardio Crusher",
        "training_type": "AMRAP",
        "description": "Lange conditie-AMRAP met hardlopen, wall balls en een farmers carry.",
        "duration_minutes": 45,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Burpee", "reps": 15},
            {"exercise_name": "DB Push Press", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "The Grinder",
        "training_type": "AMRAP",
        "description": "Mixed-modal AMRAP met bike, squats, step-ups en pull-ups.",
        "duration_minutes": 28,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Legs of Steel",
        "training_type": "AMRAP",
        "description": "Beenintensieve AMRAP met hardlopen, lunges en box jumps.",
        "duration_minutes": 26,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 600},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Box Jump", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
        ],
    },
    {
        "name": "Upper Engine",
        "training_type": "AMRAP",
        "description": "Bovenlichaam-AMRAP met roeien, pull-ups en shoulder-to-overhead.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "DB Push Press", "reps": 15},
            {"exercise_name": "Russian Twist", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
        ],
    },
    {
        "name": "Hybrid Strength",
        "training_type": "AMRAP",
        "description": "Kracht en conditie gemengd. Sandbag-onderdelen vervangen door dumbbell-varianten.",
        "duration_minutes": 26,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "DB Sumo Squat", "reps": 20},
            {"exercise_name": "Ground to Overhead", "reps": 15},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Ski Erg", "calories": 20},
        ],
    },
    {
        "name": "Grip Monster",
        "training_type": "AMRAP",
        "description": "Grip-AMRAP met carry, pull-ups en swings.",
        "duration_minutes": 26,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
        ],
    },
    {
        "name": "Full Send",
        "training_type": "AMRAP",
        "description": "Alles-of-niets AMRAP met bike, thrusters en burpees.",
        "duration_minutes": 26,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Thruster", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Long Burner AMRAP",
        "training_type": "AMRAP",
        "description": "Langere, rustige AMRAP met hardlopen en bodyweight-bewegingen.",
        "duration_minutes": 24,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 800},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Air Squat", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 500},
        ],
    },
    {
        "name": "Hyrox Beast",
        "training_type": "AMRAP",
        "description": "Zware Hyrox-stijl AMRAP. Sandbag lunges vervangen door walking lunges.",
        "duration_minutes": 30,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 1000},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 100},
            {"exercise_name": "Burpee Broad Jump", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "CrossFit Classic",
        "training_type": "AMRAP",
        "description": "Klassieke CrossFit-mix met American swings, pull-ups en squats.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 500},
            {"exercise_name": "KB Swing American", "reps": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 250},
        ],
    },
    {
        "name": "DB Madness",
        "training_type": "AMRAP",
        "description": "Volledig dumbbell-gebaseerde AMRAP. Front rack lunges vervangen door DB walking lunges.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "DB Snatch", "reps": 20},
            {"exercise_name": "DB Walking Lunge", "reps": 20},
            {"exercise_name": "DB Push Press", "reps": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Core Killer",
        "training_type": "AMRAP",
        "description": "Core-intensieve AMRAP met sit-ups, toes-to-bar en hardlopen.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "Sit-up", "reps": 25},
            {"exercise_name": "Toes-to-Bar", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Sweat Fest",
        "training_type": "AMRAP",
        "description": "Hoog-volume conditie-AMRAP.",
        "duration_minutes": 24,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "KB Swing Russian", "reps": 20},
        ],
    },
    {
        "name": "Sandbag Day",
        "training_type": "AMRAP",
        "description": "Functionele AMRAP - sandbag-onderdelen vervangen door dumbbell/kettlebell-varianten.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "DB Clean", "reps": 20},
            {"exercise_name": "DB Sumo Squat", "reps": 20},
            {"exercise_name": "KB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
        ],
    },
    {
        "name": "Mixed Modal",
        "training_type": "AMRAP",
        "description": "Brede mix van roeien, box jumps, thrusters en hardlopen.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 500},
            {"exercise_name": "Box Jump Over", "reps": 20},
            {"exercise_name": "DB Thruster", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Engine Max",
        "training_type": "AMRAP",
        "description": "Conditie-AMRAP met hardlopen, squats en wall balls.",
        "duration_minutes": 24,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 750},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Ski Erg", "calories": 20},
        ],
    },
    {
        "name": "Pull & Push",
        "training_type": "AMRAP",
        "description": "Trek- en duwkracht afgewisseld met conditie.",
        "duration_minutes": 24,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "Kipping Pull-up", "reps": 15},
            {"exercise_name": "Push-up", "reps": 20},
            {"exercise_name": "Push Press", "reps": 15},
            {"exercise_name": "Row", "distance_meters": 250},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
        ],
    },
    {
        "name": "Chipper Style",
        "training_type": "AMRAP",
        "description": "Chipper-achtige mix, gebouwd als doorlopende AMRAP.",
        "duration_minutes": 26,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Ski Erg", "distance_meters": 500},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "KB Swing Russian", "reps": 20},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Sit-up", "reps": 20},
            {"exercise_name": "Running", "distance_meters": 400},
        ],
    },
    {
        "name": "Long Legs",
        "training_type": "AMRAP",
        "description": "Lange beenintensieve AMRAP met roeien, lunges en squats.",
        "duration_minutes": 26,
        "level": "intermediate",
        "movements": [
            {"exercise_name": "Row", "distance_meters": 1000},
            {"exercise_name": "Walking Lunge", "reps": 20},
            {"exercise_name": "Box Step-Up", "reps": 20},
            {"exercise_name": "Goblet Squat", "reps": 20},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
        ],
    },
    {
        "name": "Hyrox Finisher AMRAP",
        "training_type": "AMRAP",
        "description": "Brede Hyrox-stijl afsluiter met hardlopen, wall balls en carry.",
        "duration_minutes": 28,
        "level": "advanced",
        "movements": [
            {"exercise_name": "Running", "distance_meters": 400},
            {"exercise_name": "Wall Ball Shot", "reps": 20},
            {"exercise_name": "Burpee", "reps": 20},
            {"exercise_name": "Assault Bike", "calories": 20},
            {"exercise_name": "DB Farmers Carry", "distance_meters": 100},
            {"exercise_name": "Ground to Overhead", "reps": 20},
            {"exercise_name": "Ski Erg", "distance_meters": 250},
        ],
    },
]
